
#Common
[common]
	#Fix deployers unnecessarily entering their 10-tick cooldown when milking, emptying buckets, slaughtering, etc.
	#Because the secondary output overflow check is always performed before the outputs are extracted.
	deployer_instant_output = true
	#Allows funnels to extract items positioned exactly at the center of a belt.
	#Previously, funnels could only extract items past the center.
	#When a opposing funnel blocks items at the center, all side-facing belt funnels stop extracting, which is unintuitive.
	belt_funnel_detection_tweak = true
	#Prevent Diagonal Chutes from interacting with containers below.
	#Because visually, Diagonal Chutes have no opening at the bottom.
	no_chute_leaking = true
	#Prevent the depot from dropping overflow items.
	#For example when it accumulates too many processing outputs.
	#Or when an Ejector cannot merge received item stacks.
	no_depot_overflow_drop = true
	#Allow pumps to replace any flowing fluid, ignoring the fluid type.
	replace_any_flowing_fluid = true
	#PSIs on trains are now only activated when the train arrives at a station.
	better_psi_on_carriage = true
	#Make super glue as convenient as honey glue from Aeronautic.
	hachimi_glue = true
	#Allow smart fluid pipes and valve pipes to work without being directly attached to a tank.
	#And slightly optimize the performance.
	smart_fluid_pipe = true
	#Allow belts to operate without requiring a power source.
	easy_belt = true
	#Backported the optimization from Create PR #9706. (Needs restart)
	fast_contraption_storage = true
	#Optimize the performance of various logistics components.
	fast_logistics = true
	#Show the contents of the basin faucet when wearing Goggles.
	basin_faucet_view = true

#Bugfix
[bugfix]
	#Backported the fix from Create PR #9624.
	psi_fix = true
	#Fix hose pulleys incorrectly showing "Bottomless Supply" and stopping fill 2 blocks before reaching the actual threshold;
	#Fix fluid input rates above 1000 mB/t to hose pulleys being incorrectly reduced;
	#Fix mechanical pumps with a full output deleting fluid when extracting from a hose pulley;
	#Add extra tooltip when wearing Goggles.
	hose_pulley_fix = true
	#Fix single-block tanks or vaults placed by schematic incorrectly have zero capacity.
	vault_and_tank_schematic_fix = true
	#Backported the fix from Create PR #9974 and #10001;
	#Fix open pipes being unable to place fluids when the output rate exceeds 1000 mB/t;
	#Fix open pipes not validating their connections;
	#Fix an issue where, when "mechanicalPumpRange" >= 16, long pipes may occasionally fail to rebuild their fluid network correctly after chunks are reloaded.
	fluid_network_fix = true
	#Backported the fix from Create PR #9891, #9967 and #10017;
	#Fix the issue where the outputs of belt processing machines will be pushed back to the input side by a blocked belt funnel;
	#Fix Create Issue #9682.
	belt_fix = true
	#Fix one of the two fluids output of a basin disappearing under certain conditions;
	#Fix recipe priority sorting not taking fluid ingredient amounts into account;
	#Fix basin recipe filtering only considering the first output of recipes with multiple outputs;
	#Fix sequenced assembly recipes using incorrect steps under certain conditions.
	processing_fix = true
	#Backported the fix from Create PR #9875 and #10362;
	#Attempt to fix the issue where trains sometimes cause crashes;
	#Fix an issue where trains never release their reserved signal segment, causing a deadlock.
	train_fix = true
	#Backported the fix from Create PR #9649 and #9793.
	logistics_fix = true
	#Backported the fix from Create PR #9729
	fix_9729 = true
	#Backported the fix from Create PR #9803
	fix_9803 = true

#Misc
[misc]
	#Player won't drown underwater.
	player_can_breath_underwater = false
	#When players are in the air or water, they will no longer be subject to a five-time increase in digging time penalty
	disable_dig_speed_penalty = false
	#Allow all players flying.
	always_allow_flying = false
	#Prevents players from automatically exiting flight mode when touching the ground.
	keep_flying_on_ground = false
	#Allow rotation for blocks without a custom rotate implementation.
	#Many mod authors do not override rotate and mirror when adding directional blocks.
	#As a result, vanilla structure block placement and Create schematic printing are unable to correctly rotate these blocks.
	#Enabling this feature automatically detects common facing properties and applies rotation/mirror.
	heuristic_rotation = true

