const $AllGuiTextures = Java.loadClass('com.simibubi.create.foundation.gui.AllGuiTextures')
const $AnimatedKinetics = Java.loadClass('com.simibubi.create.compat.jei.category.animations.AnimatedKinetics')
const $AllPartialModels = Java.loadClass('com.simibubi.create.AllPartialModels')
const $CreateRecipeCategory = Java.loadClass('com.simibubi.create.compat.jei.category.CreateRecipeCategory')
const $Axis = Java.loadClass('com.mojang.math.Axis')
const $DoubleItemIcon = Java.loadClass('com.simibubi.create.compat.jei.DoubleItemIcon')
const $RecipeIngredientRole = Java.loadClass('mezz.jei.api.recipe.RecipeIngredientRole')
const $ItemIcon = Java.loadClass('com.simibubi.create.compat.jei.ItemIcon')
